### ISSUE TITLE
Citations can't be enable on multijournal OJS 3.2.1-1

### ISSUE THREAD

**Issue by gurumelo** [RBoelter/citations#5]
Hello.

OJS multjournal.

I installed scopus/crossref plugin but it doesn't appear on plugins list to enable on journals.

Thanks

**Comment by RBoelter** [comment]
Hi,
wich plugin list do you mean? `Administration -> Site Settings -> Plugins` or `<Your Journal> -> Settings -> Website -> Plugins`?
It is not possible to enable or configure the plugin via `Administration -> Site Settings -> Plugins` , because the "isSitePlugin" options is disabled. You have to enable the plugin for each journal via `<Your Journal> -> Settings -> Website -> Plugins`. The reason for this is that the credentials for crossref or scopus sometimes differ from journal to journal.

**Comment by gurumelo** [comment]
Hi @RBoelter . Thanks for your respond.

it's via ```<Your Journal> -> Settings -> Website -> Plugins``` 

I "discovered" something.

If you have english language, i can enable plugin on journals, if i have another language, i can't see the plugin on the list.

Thanks

**Comment by RBoelter** [comment]
You should have the Plugin in list, but it looks like `##plugins.generic.citations.title##`
This is because it currently only supports English and German.
If you prefer another language, it would be great if you could add this to the plugin.
This is very easy, just download: https://github.com/RBoelter/citations/blob/master/locale/en_US/locale.po
Change the text in the `msgstr` to your language and attach the file here in the comments. 
I'll add the language in the new version.

**Comment by RBoelter** [comment]
Or do a pull request if you prefer this way.

**Comment by gurumelo** [comment]
https://github.com/RBoelter/citations/pull/6

**Comment by RBoelter** [comment]
This is great, thank you very much!
I will update the plugin in the PKP plugin gallery at the end of the week.

**Comment by RBoelter** [comment]
New version is on its way ;-) 

https://github.com/pkp/plugin-gallery/pull/44
